🔀 :: (#99) 선생님 인증코드 재발급
EntryDSM/Raise-Percent pull request #106
Opened 2022-01-08 14:23 UTC by softpeanut

2022-01-08 15:13 UTC, eogus2513 approved these changes

2022-01-09 10:53 UTC, leeseojune53 requested changes

2022-01-09 10:53 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeReissueService.java
> +                        .build());
이 코드 보다는 Optional.of를 활용한 문법이 더 깔끔할 것 같아요

아래는 예시입니다.
codeRepository.findById(id)
.or(Optional.of(new Code(~~,~~)))
.map(code -> code.updateCode(newCode);

2022-01-09 10:53 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/QueryCodeService.java
> +    private String id;
굿굿 :)

2022-01-09 12:47 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeReissueService.java
> +                        .build());
저 궁금한 점이 있는데 or함수가 실행된 후에 map함수도 실행이 되는건가요?

2022-01-09 13:36 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeReissueService.java
> +                        .build());
정현 선배가 달았어요..

2022-01-10 03:06 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeReissueService.java
> +                        .build());
저게 무슨 소리여

2022-01-10 03:07 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeReissueService.java
> +                        .build());
실제 객체를 map으로 가져오는겨
repository에서 없으면 Optional.of로 객체를 생성해서 map으로 가는거고
있으면 바로 map으로 가는겨

2022-01-10 04:48 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeReissueService.java
> +                        .build());
Optional<Code>를 Code로 어떻게 꺼냄?

2022-01-10 08:54 UTC, glay415 approved these changes

2022-01-10 09:05 UTC, leeseojune53 approved these changes

2022-01-10 09:09 UTC, merged