🔀 :: (#85) show feedback
EntryDSM/Raise-Percent pull request #108
Opened 2022-01-08 14:36 UTC by eogus2513

2022-01-08 15:01 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/global/entity/BaseDocumentContentEntity.java
> +@AllArgsConstructor
테스트 때문에 추가된 것이라면 지우는게 더 좋을 것 같습니다

2022-01-08 15:02 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/facade/FeedbackFacade.java
> +    public Feedback getCurrentFeedback(UUID id) {
그럼 뭐로 바꾸는게 좋을까요?

2022-01-08 15:02 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/dto/response/ShowFeedbackResponse.java
> +    private String content;
수정하겠습니다.

2022-01-08 15:04 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/global/entity/BaseDocumentContentEntity.java
> +@AllArgsConstructor
@AllArgsConstructor 안붙이면 @SuperBuilder에서 에러가 나서 저렇게 했습니다.

2022-01-08 15:04 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/facade/FeedbackFacade.java
> +    public Feedback getCurrentFeedback(UUID id) {
uuid로 그냥 조회하는 거라 그냥 getFeedback은 어떤가요?

2022-01-08 15:04 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/facade/FeedbackFacade.java
> +    public Feedback getCurrentFeedback(UUID id) {
오오 아주 좋아요

2022-01-09 08:01 UTC, softpeanut approved these changes

2022-01-09 08:07 UTC, softpeanut commented
FeedbackFacade랑 BaseDocumentContentEntity랑 AuthDetails 테스트 해주세요 ㅎ

2022-01-09 10:49 UTC, leeseojune53 requested changes

2022-01-09 10:49 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/global/entity/BaseDocumentContentEntity.java
> +@AllArgsConstructor
access로 접근제한해도 좋을 것 같아요

2022-01-09 10:49 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetails.java
> +@Getter
Getter를 추가한 이유가 무엇일까요?

2022-01-09 12:53 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/global/entity/BaseDocumentContentEntity.java
> +@AllArgsConstructor
@AllArgsConstructor(access = AccessLevel.PROTECTED)
이렇게 수정할까요?

2022-01-09 13:39 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetails.java
> +@Getter
ShowFeedbackService에서 authFacade.getCurrentDetails().getRole() == Type.STUDENT이 부분때문에 붙였어요

2022-01-10 03:07 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/global/entity/BaseDocumentContentEntity.java
> +@AllArgsConstructor
네네 좋아요

2022-01-10 03:08 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetails.java
> +@Getter
음.. 그 부분은 authories에 넣어놔서 SecurityConfig에서 hasRole 또는 hasAnyRole로 처리하는게 맞을 것 같습니다.

2022-01-10 03:38 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetails.java
> +@Getter
저렇게 한 이유가 securityConfig에서 Student, Root로 거른다음에 Student는 해당학생만 봐야 한다고 해서 Role이 Student이면 저 if문에서 해당학생인지 거르는 처리를 했습니다.

2022-01-10 04:29 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetails.java
> +@Getter
굿굿 :)

2022-01-10 04:29 UTC, leeseojune53 requested changes

2022-01-10 04:29 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/ShowFeedbackService.java
> +        }
Type.STUDENT.equals(authFacade~~~)로 변경하는게 더 좋을 것 같아요

2022-01-10 04:35 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/ShowFeedbackService.java
> +        }
수정하겠습니다.

2022-01-10 10:48 UTC, softpeanut approved these changes

2022-01-10 11:24 UTC, leeseojune53 approved these changes

2022-01-10 12:19 UTC, merged