🔀 :: (#123) 피드백 수정
EntryDSM/Raise-Percent pull request #125
Opened 2022-01-11 10:32 UTC by eogus2513

2022-01-11 10:36 UTC, leeseojune53 requested changes

2022-01-11 10:36 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/CreateFeedbackService.java
> +        Document document = documentFacade.getDocument(UUID.fromString(id));
난 반댈세

2022-01-11 10:36 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/ShowFeedbackService.java
> +        Feedback feedback = feedbackFacade.getFeedback(UUID.fromString(id));
나는 반대란 마링여

2022-01-11 10:36 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/UpdateFeedbackService.java
> +        Feedback feedback = feedbackFacade.getFeedback(UUID.fromString(id));
이~~ 뭐하는거야

2022-01-11 10:36 UTC, leeseojune53 commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/ShowFeedbackServiceTest.java
> +        String id = String.valueOf(UUID.randomUUID());
toString

2022-01-11 10:38 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
> +    public void createFeedback(@PathVariable("document-id") String id,
UUID를 파라미터로 못 받나요???

2022-01-11 10:38 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
> +    public void createFeedback(@PathVariable("document-id") String id,
받을수있음

2022-01-11 10:39 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
> +    public void createFeedback(@PathVariable("document-id") String id,
그 서준선배가 하신 거 보니깐 UUID를 파라미터로 안받고 String로 받으시고 UUID로 변환하셔서 저도 똑같이 따라하긴 했어요..

2022-01-11 10:39 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
> +    public void createFeedback(@PathVariable("document-id") String id,
받을수는있음

2022-01-11 10:40 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
> +    public void createFeedback(@PathVariable("document-id") String id,
이유를 모르고한겨?

2022-01-11 10:50 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
> +    public void createFeedback(@PathVariable("document-id") String id,
잘 모르겠어요...

2022-01-11 10:51 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
> +    public void createFeedback(@PathVariable("document-id") String id,
저거는 UUID로 받으면 UUID가 아닌게 들어오면 handling을 따로해야함. Filter를 두던가해서 그래서 일단 String으로 받고, service layer에서 변환하는겨

2022-01-11 10:52 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
> +    public void createFeedback(@PathVariable("document-id") String id,
오옹!

2022-01-11 11:09 UTC, leeseojune53 approved these changes

2022-01-12 00:56 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
> +    public void createFeedback(@PathVariable("document-id") String id,
근데 filter를 두는게 더 깔끔하지 않어?? 안그러면 UUID를 받는 모든 곳에서 저렇게 핸들링을 해야하는거잖아 나는 반댈세

2022-01-12 13:37 UTC, softpeanut approved these changes

2022-01-12 14:24 UTC, merged