🔀 :: (#134) 제출한 문서 리스트
EntryDSM/Raise-Percent pull request #135
Opened 2022-01-12 14:35 UTC by softpeanut

close #134

2022-01-12 14:41 UTC, softpeanut commented
아직 못한 테스트는 추가적으로 하겠습니다

2022-01-12 23:38 UTC, eogus2513 approved these changes

2022-01-13 05:36 UTC, eogus2513 approved these changes

2022-01-13 07:13 UTC, glay415 approved these changes

2022-01-14 05:02 UTC, leeseojune53 requested changes

2022-01-14 05:02 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacade.java
> +                        .number(document.getDocument().getStudent().getNumber())
여기 조금 불편..

2022-01-14 05:02 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/QuerySubmittedDocumentListService.java
> +    @Transactional(readOnly = true)
readOnly 넣은 이유는 뭔가요?

2022-01-14 05:29 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/QuerySubmittedDocumentListService.java
> +    @Transactional(readOnly = true)
조회만 할 때 readOnly를 넣으면 영속성 컨텍스트의 메모리 사용량을 최적화할 수 있다고 봐서 넣었습니다

2022-01-14 05:29 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacade.java
> +                        .number(document.getDocument().getStudent().getNumber())
document.getDocument().getStudent()를 묶을까요?
짜다보니까 저런 식으로밖에 안나와서..
좋은 방법이 있을까요

2022-01-14 18:44 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacade.java
> +                        .number(document.getDocument().getStudent().getNumber())
ㄴㄴ Document내부에 getUserName, getNumber같은 메서드를 만들어서 디미터 법칙을 준수하는게 좋을 듯

2022-01-14 18:46 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/QuerySubmittedDocumentListService.java
> +    @Transactional(readOnly = true)
굿

2022-01-14 18:46 UTC, leeseojune53 approved these changes

2022-01-15 01:12 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacade.java
> +                        .number(document.getDocument().getStudent().getNumber())
하이톤만 끝나고 수정하겠습니다 ㅎㅎ..

2022-01-17 07:43 UTC, merged