133 get login link
EntryDSM/Raise-Percent pull request #155
Opened 2022-02-04 13:49 UTC by WilterFlip

2022-02-04 14:15 UTC, eogus2513 commented
제목 형식에 맞게 수정부탁드립니다.

2022-02-06 02:15 UTC, syxxn approved these changes

2022-02-06 02:15 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/facade/HrFacade.java
> +
코드 스타일일 수도 있는데, 보통 메소드의 시작과 끝에서는 공백을 두지 않아요!
이 레포지토리 내의 다른 서비스를 봐도 다 그렇게 작성 되어있구요
자바 코드 컨벤션 한 번 찾아보면 좋을 것 같아요
![image](https://user-images.githubusercontent.com/64132926/152665276-a54e116c-52c3-4449-a3cc-2840273c85c6.png)

2022-02-06 02:15 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/presentation/HrController.java
> +@RequiredArgsConstructor
어노테이션 순서도 다른 것과 맞추는 게 유지보수하는 입장에서 편할 것 같아요.
보통 롬복 어노테이션을 맨 위에 두는데, 롬복은 길이순으로 정렬합니당. 그리고 가장 핵심이 된다고 생각하는 어노테이션을 클래스(또는 메소드)와 가깝게 둬요!

2022-02-06 02:15 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/presentation/HrController.java
> +@RequestMapping("/managers")
base url은 /managers인데, 패키지 명은 hr로 설정한 이유가 있나요?

2022-02-06 02:15 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/presentation/TeacherController.java
> +import kr.hs.entrydsm.raisepercent.global.util.auth.service.QueryGoogleAuthLinkService;
다음엔 패키지 옮기는 이슈는 따로 파서 관리해주시면 좋을 것 같습니당:)

2022-02-06 06:23 UTC, leeseojune53 requested changes

2022-02-06 06:23 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/domain/types/HrType.java
> +}
이건 어떤 이유로 만든건가요?

2022-02-06 06:23 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/domain/types/HrType.java
> +}
기존에 Type를 만들었습니다.

2022-02-07 02:54 UTC, WilterFlip commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/presentation/HrController.java
> +@RequestMapping("/managers")
패키지 설정은 제가 안 해서 저도 잘 모르지만, 인사담당자 테이블 명(tbl_hr)에 따라 이렇게 된 것 같습니다.

2022-02-07 04:35 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/domain/types/HrType.java
> +}
현재 사용하고있지않은것같은데 삭제하지않는 이유가있을까요?

2022-02-07 04:46 UTC, WilterFlip commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/domain/types/HrType.java
> +}
방금 커밋에서, 삭제 했습니다!!

2022-02-07 06:50 UTC, leeseojune53 approved these changes

2022-02-07 23:40 UTC, eogus2513 approved these changes

2022-02-08 02:33 UTC, glay415 approved these changes

2022-02-08 03:19 UTC, softpeanut approved these changes

2022-02-10 04:58 UTC, merged