🔀 :: (#161) 공개 문서 조회 api
EntryDSM/Raise-Percent pull request #162
Opened 2022-02-08 01:41 UTC by glay415

2022-02-08 02:43 UTC, softpeanut requested changes

2022-02-08 02:43 UTC, softpeanut commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/QueryPublicDocumentDetailsServiceTest.java
> +class QueryPublicDocumentDetailsServiceTest {
테스트 형식 BDD로 바꿔주세요

2022-02-08 02:49 UTC, glay415 commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/QueryPublicDocumentDetailsServiceTest.java
> +class QueryPublicDocumentDetailsServiceTest {
얘도요 일단 머지된다음 하겠습니다

2022-02-08 03:00 UTC, glay415 commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/QueryPublicDocumentDetailsServiceTest.java
> +class QueryPublicDocumentDetailsServiceTest {
아 이친구는 바꿔야겠네요

2022-02-08 03:09 UTC, glay415 commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/QueryPublicDocumentDetailsServiceTest.java
> +class QueryPublicDocumentDetailsServiceTest {
@InjectMoc등으로 변경하는거도 해야해서 한번에 하는게 낳을거 같습니다

2022-02-08 06:02 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/QueryPublicDocumentDetailsService.java
> +		documentFacade.checkIsEmpty(publicDocuments);
여기 코드가 list가 empty하면 Exception을 던지는거를 명확하게 모르겠음

2022-02-08 23:43 UTC, softpeanut approved these changes

2022-02-15 13:27 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/PublicDocumentRepository.java
> +	List<PublicDocument> findByIdDocumentId(UUID documentId);
findBy(매개변수)로 보통 쓰지 않나요? id가 따로 안 들어가는 것 같은데 메소드명을 이렇게 설정하신 이유가 있을까요?

2022-02-16 07:43 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/PublicDocumentRepository.java
> +	List<PublicDocument> findByIdDocumentId(UUID documentId);
저게 복합키라서 네이밍을 복합키 명(id)+복합키 객체 내부 필드 명(documentId)를 해서 저렇게된거예요

2022-02-16 07:54 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/PublicDocumentRepository.java
> +	List<PublicDocument> findByIdDocumentId(UUID documentId);
말이 조금 복잡한데, 우선 PublicDocument(Document)의 id로 찾는데, 거기서 Document라는 필드의 Id를 찾는 네이밍임

2022-02-17 08:06 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/PublicDocumentRepository.java
> +	List<PublicDocument> findByIdDocumentId(UUID documentId);
아하 답변 감사합니당

2022-02-20 08:55 UTC, eogus2513 approved these changes

2022-02-27 03:42 UTC, WilterFlip approved these changes

2022-02-27 12:26 UTC, merged