🔀 :: (#189) refresh token
EntryDSM/Raise-Percent pull request #190
Opened 2022-03-11 14:41 UTC by eogus2513

2022-03-11 15:04 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenService.java
> +    private TokenResponse generateTokens(String email, TokenRole tokenRole) {
TokensResponse라고는 안하면서 왜 메소드명은 generateTokens인가욤?

2022-03-11 15:04 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenService.java
> +    public TokenResponse execute(String token) {
들어온 토큰이 refresh token이 맞는지는 따로 검사 안하나요?

2022-03-11 15:04 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
> -    OTHER_BAD_REQUEST(400, "OTHER-400-1", "Other server bad request"),
이런거 지워져도 되는 코드예요??

2022-03-11 15:04 UTC, syxxn commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/user/exception/TokenNotFoundExceptionTest.java
> +        assertEquals(ErrorCode.TOKEN_NOT_FOUND, TokenNotFoundException.EXCEPTION.getErrorCode());
명세보면 만료되었거나 잘못된 형식일때는 401을 반환한다고 했었는데 왜 야는 잘못된 토큰인데 404로 반환해염

2022-03-12 02:22 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenService.java
> +    private TokenResponse token(String email) {
메소드 이름이...

2022-03-12 02:22 UTC, softpeanut commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenServiceTest.java
> +        when(studentRepository.findById(email))
이거 BDD형식으로 하는 게 좋을 것 같아요

2022-03-12 02:32 UTC, leeseojune53 requested changes

2022-03-12 02:32 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenService.java
> +        }
token에 claims 'role'에 어떤 역할인지 들어가있어요
JwtTokenProvider에서 getRole같은 method 만들어서 토큰에서 가져오는게 더 효율적일 것 같아요.

2022-03-12 02:34 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenService.java
> +        }
JwtTokenProvider에서 role를 가져와서 그걸로 토큰을 가져오라는 말씀인거죠?

2022-03-12 02:40 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenService.java
> +        }
네네

2022-03-12 02:41 UTC, softpeanut commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenServiceTest.java
> +        assertThrows(UserNotFoundException.class, () -> service.execute(token));
이거 준서가 묶은 것처럼 따로 메소드로 빼서 this::메소드 이런식으로 하는 것도 좋아 보이네요

2022-03-12 06:26 UTC, eogus2513 commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenServiceTest.java
> +        assertThrows(UserNotFoundException.class, () -> service.execute(token));
자세하게 설명해주실 수 있나요?

2022-03-12 10:46 UTC, softpeanut commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenServiceTest.java
> +        assertThrows(UserNotFoundException.class, () -> service.execute(token));
서비스를 호출하는 부분을 private 메소드로 빼고 현재 람다식으로 서비스를 호출하는 부분에서는 this::(private 메소드) 이런식으로 호출하는 것입니다

2022-03-12 10:56 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenService.java
> +        throw UserNotFoundException.EXCEPTION;
이 부분은 그냥 generateTokens(email, role)하면 되는거 아닌가요?

2022-03-12 10:56 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenService.java
> +        throw UserNotFoundException.EXCEPTION;
굳이 더블체크할필요가있나 궁금함

2022-03-13 08:02 UTC, leeseojune53 approved these changes

2022-03-13 23:41 UTC, syxxn approved these changes

2022-03-14 00:02 UTC, softpeanut approved these changes

2022-03-14 00:03 UTC, merged