🔀 :: (#12) 피드백 작성 api
EntryDSM/Raise-Percent pull request #84
Opened 2022-01-06 01:28 UTC by eogus2513

2022-01-06 04:27 UTC, leeseojune53 commented
Exception 테스트도 작성 부탁드립니다

2022-01-06 04:30 UTC, leeseojune53 requested changes

2022-01-06 04:30 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/facade/TeacherFacade.java
> +    }
이 부분 다른부분에서도 중복되지않나요??
AuthFacade쪽을 public으로 바꾸고 재사용하는 것도 좋을것같아요

2022-01-06 04:55 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/dto/request/CreateFeedbackRequest.java
> +@AllArgsConstructor
request에 @AllArgsConstructor가 필요하나요?

2022-01-06 04:55 UTC, softpeanut commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacadeTest.java
> +public class DocumentFacadeTest {
공백인가요??

2022-01-06 04:56 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/dto/request/CreateFeedbackRequest.java
> +@AllArgsConstructor
딱히 필요없어 보여요
수정하겠습니다.

2022-01-06 04:56 UTC, eogus2513 commented on src/test/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacadeTest.java
> +public class DocumentFacadeTest {
수정하겠습니다.

2022-01-06 06:47 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/facade/TeacherFacade.java
> +    }
AuthFacade만들어서 바꾸도록 하겠습니다.

2022-01-06 15:50 UTC, eogus2513 commented
@leeseojune53 Exception 예외 Test까지 다 만들었습니다.

2022-01-06 16:26 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/dto/request/CreateFeedbackRequest.java
> +}
개행해주세요 ㅎ

2022-01-06 16:26 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/facade/TeacherFacade.java
> +    public Teacher getTeacher() {
getCurrentTeacher로 바꾸는게 더 알아보기 쉬울 것 같아요

2022-01-06 16:27 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/dto/request/CreateFeedbackRequest.java
> +}
수정하겠습니다.

2022-01-06 16:30 UTC, leeseojune53 commented
Facade test 바랍니다

2022-01-06 16:31 UTC, eogus2513 commented
@leeseojune53 어떤 Facade를 말하는 건가요?

2022-01-06 16:39 UTC, leeseojune53 commented
DocumentFacade, TeacherFacade입니다.

2022-01-06 23:51 UTC, eogus2513 commented
@leeseojune53 추가했습니다.

2022-01-06 23:58 UTC, syxxn approved these changes

2022-01-07 00:13 UTC, softpeanut approved these changes

2022-01-07 05:14 UTC, leeseojune53 approved these changes

2022-01-07 05:31 UTC, merged